package DAO;

import console.Console;
import console.SystemConsole;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;

public class DAOcity implements DAO, Iterable<String> {
    private final List<String> citiesDest = Arrays.asList("New York",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Baku",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Kiev",
            "San Jose",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Baku",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Baku",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Baku",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Baku",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Baku",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Baku",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Baku",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Baku",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Baku",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Kiev",
            "San Jose",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Baku",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Baku",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Baku",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Baku",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Baku",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Baku",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Baku",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Baku",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Baku",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Kiev",
            "San Jose",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Baku",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Baku",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Baku",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Baku",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Baku",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Baku",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Baku",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Baku",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Baku",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Kiev",
            "San Jose",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Baku",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Baku",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Baku",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Baku",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Baku",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Baku",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Baku",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Baku",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose");
    private final List<String> citiesSrc = Arrays.asList("Baku",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Baku",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Kiev",
            "San Jose",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Baku",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Baku",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Baku",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Baku",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Baku",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Baku",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Baku",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Baku",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Baku",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Kiev",
            "San Jose",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Baku",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Baku",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Baku",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Baku",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Baku",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Baku",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Baku",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Baku",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Baku",
            "Baku",
            "Kharkiv",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Baku",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "Baku",
            "Chicago",
            "Houston",
            "Phoenix",
            "Baku",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Baku",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Kiev",
            "San Jose",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Baku",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Baku",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Baku",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Baku",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Baku",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Baku",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Baku",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Baku",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Baku",
            "Dallas",
            "San Jose",
            "Austin",
            "Baku",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Baku",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Chicago",
            "Baku",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "Baku",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Baku",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Seattle",
            "Almaty",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Miami",
            "Paris",
            "Phoenix",
            "Naxchivan",
            "Kiev",
            "Baku",
            "Hong Kong",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Moscow",
            "Nagasaki",
            "Denver",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Washington",
            "Boston",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Almaty",
            "Baku",
            "Sumqayit",
            "Kiev",
            "Baku",
            "Hong Kong",
            "Egypt",
            "Istanbul",
            "Beijing",
            "Mexico");
    Console console = new SystemConsole();
    private String fPath = "src/main/destCities.txt";
    private String pFath = "src/main/srcCities.txt";

    public List<String> getCitiesSrc() {
        return citiesSrc;
    }

    public void create() {
        try (BufferedWriter wb = new BufferedWriter(new FileWriter(pFath));
             BufferedWriter bw =
                     new BufferedWriter(new FileWriter(fPath))) {
            citiesDest.forEach(c -> {
                try {
                    bw.write(c);
                    bw.newLine();


                } catch (IOException e) {
                    console.printLn("Couldn't update the file for cities");
                }

            });
            citiesSrc.forEach(c -> {
                try {
                    wb.write(c);
                    wb.newLine();

                } catch (IOException e) {
                }
            });
            bw.flush();
            wb.flush();
        } catch (IOException e) {
            console.printLn("Couldn't create the file for cities");
        }
    }

    @Override
    public Object get(int id) {
        return citiesDest.get(id);
    }

    @Override
    public List getAll() {
        return citiesDest;
    }

    @Override
    public void put(Object o) {
        citiesDest.add(o.toString());
    }

    @Override
    public void delete(int id) {
        citiesDest.remove(id);
    }

    @Override
    public Iterator<String> iterator() {
        return citiesDest.iterator();
    }
}
